name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          ubuntu-18.04
        ]
        include:
          - name: ubuntu-18.04
            os: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install
      run: |
        wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -O /tmp/devkitpro-pacman.deb
        sudo dpkg -i /tmp/devkitpro-pacman.deb
        yes | sudo dkp-pacman -Syu --needed devkitPPC wut-tools
        echo ::set-env name=DEVKITPRO::/opt/devkitpro
        echo ::set-env name=DEVKITPPC::/opt/devkitpro/devkitPPC
        echo ::set-env name=PATH::$DEVKITPRO/tools/bin:$DEVKITPPC/bin:$PATH

    - name: Build
      run: |
        make -j2
        sudo -E make install

    - name: Build Test
      run: |
        cd tests
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$DEVKITPRO/wut/share/wut.toolchain.cmake ../
        make -j2

    - name: Build Samples (Make)
      run: |
        cd samples/make
        make -j2

    - name: Build Samples (CMake)
      run: |
        cd samples/cmake
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$DEVKITPRO/wut/share/wut.toolchain.cmake ../
        make -j2
